/*
 *   Copyright 2016-2026. Couchbase, Inc.
 *   All Rights Reserved.
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

// ====================================================================================================
// AUTOGENERATED FILE START - DO NOT EDIT MANUALLY
// Generated-On: 2026-04-25 14:10:18
// ====================================================================================================

#pragma once
#define PY_SSIZE_T_CLEAN
#include <Python.h>

namespace pycbc
{
namespace keys
{

extern PyObject* access_deleted;
extern PyObject* all_okay;
extern PyObject* array_positions;
extern PyObject* batch_byte_limit;
extern PyObject* batch_item_limit;
extern PyObject* batch_time_limit;
extern PyObject* body;
extern PyObject* bucket;
extern PyObject* callback;
extern PyObject* cas;
extern PyObject* client_context_id;
extern PyObject* code;
extern PyObject* collection;
extern PyObject* collection_id;
extern PyObject* collection_name;
extern PyObject* complete;
extern PyObject* concurrency;
extern PyObject* consistent_with;
extern PyObject* content;
extern PyObject* count;
extern PyObject* create_as_deleted;
extern PyObject* datatype;
extern PyObject* date_ranges;
extern PyObject* debug_info;
extern PyObject* deleted;
extern PyObject* delta;
extern PyObject* document_exists;
extern PyObject* durability_level;
extern PyObject* ec;
extern PyObject* effective_projections;
extern PyObject* elapsed_time;
extern PyObject* end;
extern PyObject* end_offset;
extern PyObject* errback;
extern PyObject* error_count;
extern PyObject* error_partition_count;
extern PyObject* errors;
extern PyObject* exclusive;
extern PyObject* execution_time;
extern PyObject* exists;
extern PyObject* expiry;
extern PyObject* explanation;
extern PyObject* field;
extern PyObject* fields;
extern PyObject* flags;
extern PyObject* fragments;
extern PyObject* from;
extern PyObject* id;
extern PyObject* ids_only;
extern PyObject* index;
extern PyObject* initial_value;
extern PyObject* is_replica;
extern PyObject* key;
extern PyObject* limit;
extern PyObject* locations;
extern PyObject* lock_time;
extern PyObject* max;
extern PyObject* max_score;
extern PyObject* message;
extern PyObject* metrics;
extern PyObject* min;
extern PyObject* missing;
extern PyObject* more;
extern PyObject* mutation_count;
extern PyObject* name;
extern PyObject* numeric_ranges;
extern PyObject* opcode;
extern PyObject* original_index;
extern PyObject* other;
extern PyObject* parent_span;
extern PyObject* path;
extern PyObject* persist_to;
extern PyObject* position;
extern PyObject* prefix;
extern PyObject* preserve_array_indexes;
extern PyObject* preserve_expiry;
extern PyObject* processed_objects;
extern PyObject* profile;
extern PyObject* projections;
extern PyObject* read_preference;
extern PyObject* reason;
extern PyObject* replica;
extern PyObject* replicate_to;
extern PyObject* request_id;
extern PyObject* result_count;
extern PyObject* result_size;
extern PyObject* retry;
extern PyObject* revive_document;
extern PyObject* scan_type;
extern PyObject* scan_uuid;
extern PyObject* scope;
extern PyObject* scope_name;
extern PyObject* score;
extern PyObject* seed;
extern PyObject* sequence_number;
extern PyObject* sequence_number_exists;
extern PyObject* signature;
extern PyObject* snapshot_requirements;
extern PyObject* sort_count;
extern PyObject* specs;
extern PyObject* start;
extern PyObject* start_offset;
extern PyObject* status;
extern PyObject* store_semantics;
extern PyObject* success_partition_count;
extern PyObject* term;
extern PyObject* terms;
extern PyObject* timeout;
extern PyObject* to;
extern PyObject* token;
extern PyObject* tokens;
extern PyObject* took;
extern PyObject* total;
extern PyObject* total_rows;
extern PyObject* value;
extern PyObject* vbucket_uuid;
extern PyObject* warning_count;
extern PyObject* warnings;
extern PyObject* with_expiry;
extern PyObject* wrapper_span_name;

} // namespace keys
} // namespace pycbc

void
init_pycbc_dict_keys();

// ====================================================================================================
// AUTOGENERATED FILE END - DO NOT EDIT MANUALLY
// Generated-On: 2026-04-25 14:10:18
// ====================================================================================================
