/*
 *   Copyright 2016-2026. Couchbase, Inc.
 *   All Rights Reserved.
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

// ====================================================================================================
// AUTOGENERATED FILE START - DO NOT EDIT MANUALLY
// Generated-On: 2026-08-12 14:50:38
// ====================================================================================================

#include "pycbc_kv_request.hxx"

namespace pycbc
{

static void
pycbc_kv_request__dealloc__(pycbc_kv_request* self)
{
  Py_XDECREF(self->bucket);
  Py_XDECREF(self->scope);
  Py_XDECREF(self->collection);
  Py_XDECREF(self->key);
  Py_XDECREF(self->access_deleted);
  Py_XDECREF(self->cas);
  Py_XDECREF(self->create_as_deleted);
  Py_XDECREF(self->delta);
  Py_XDECREF(self->durability_level);
  Py_XDECREF(self->effective_projections);
  Py_XDECREF(self->expiry);
  Py_XDECREF(self->flags);
  Py_XDECREF(self->initial_value);
  Py_XDECREF(self->lock_time);
  Py_XDECREF(self->persist_to);
  Py_XDECREF(self->preserve_array_indexes);
  Py_XDECREF(self->preserve_expiry);
  Py_XDECREF(self->projections);
  Py_XDECREF(self->read_preference);
  Py_XDECREF(self->replicate_to);
  Py_XDECREF(self->revive_document);
  Py_XDECREF(self->specs);
  Py_XDECREF(self->store_semantics);
  Py_XDECREF(self->timeout);
  Py_XDECREF(self->value);
  Py_XDECREF(self->with_expiry);
  Py_XDECREF(self->parent_span);
  Py_XDECREF(self->wrapper_span_name);
  Py_XDECREF(self->callback);
  Py_XDECREF(self->errback);
  Py_XDECREF(self->with_metrics);
  free_heap_type_instance(reinterpret_cast<PyObject*>(self));
}

static PyObject*
pycbc_kv_request__new__(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
  pycbc_kv_request* self;
  self = (pycbc_kv_request*)PyType_GenericAlloc(type, 0);
  if (self != nullptr) {
    self->opcode = 0;
    self->bucket = nullptr;
    self->scope = nullptr;
    self->collection = nullptr;
    self->key = nullptr;
    self->access_deleted = nullptr;
    self->cas = nullptr;
    self->create_as_deleted = nullptr;
    self->delta = nullptr;
    self->durability_level = nullptr;
    self->effective_projections = nullptr;
    self->expiry = nullptr;
    self->flags = nullptr;
    self->initial_value = nullptr;
    self->lock_time = nullptr;
    self->persist_to = nullptr;
    self->preserve_array_indexes = nullptr;
    self->preserve_expiry = nullptr;
    self->projections = nullptr;
    self->read_preference = nullptr;
    self->replicate_to = nullptr;
    self->revive_document = nullptr;
    self->specs = nullptr;
    self->store_semantics = nullptr;
    self->timeout = nullptr;
    self->value = nullptr;
    self->with_expiry = nullptr;
    self->parent_span = nullptr;
    self->wrapper_span_name = nullptr;
    self->callback = nullptr;
    self->errback = nullptr;
    self->with_metrics = nullptr;
  }
  return (PyObject*)self;
}

static PyMemberDef pycbc_kv_request_members[] = {
  { "opcode", Py_T_INT, offsetof(pycbc_kv_request, opcode), 0, "operation opcode" },
  { "bucket", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, bucket), 0, "bucket name" },
  { "scope", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, scope), 0, "scope name" },
  { "collection", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, collection), 0, "collection name" },
  { "key", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, key), 0, "document key" },
  { "access_deleted",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, access_deleted),
    0,
    "access_deleted" },
  { "cas", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, cas), 0, "cas" },
  { "create_as_deleted",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, create_as_deleted),
    0,
    "create_as_deleted" },
  { "delta", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, delta), 0, "delta" },
  { "durability_level",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, durability_level),
    0,
    "durability_level" },
  { "effective_projections",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, effective_projections),
    0,
    "effective_projections" },
  { "expiry", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, expiry), 0, "expiry" },
  { "flags", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, flags), 0, "flags" },
  { "initial_value",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, initial_value),
    0,
    "initial_value" },
  { "lock_time", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, lock_time), 0, "lock_time" },
  { "persist_to", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, persist_to), 0, "persist_to" },
  { "preserve_array_indexes",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, preserve_array_indexes),
    0,
    "preserve_array_indexes" },
  { "preserve_expiry",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, preserve_expiry),
    0,
    "preserve_expiry" },
  { "projections", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, projections), 0, "projections" },
  { "read_preference",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, read_preference),
    0,
    "read_preference" },
  { "replicate_to", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, replicate_to), 0, "replicate_to" },
  { "revive_document",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, revive_document),
    0,
    "revive_document" },
  { "specs", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, specs), 0, "specs" },
  { "store_semantics",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, store_semantics),
    0,
    "store_semantics" },
  { "timeout", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, timeout), 0, "timeout" },
  { "value", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, value), 0, "value" },
  { "with_expiry", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, with_expiry), 0, "with_expiry" },
  { "parent_span", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, parent_span), 0, "parent span" },
  { "wrapper_span_name",
    Py_T_OBJECT_EX,
    offsetof(pycbc_kv_request, wrapper_span_name),
    0,
    "wrapper span name" },
  { "callback", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, callback), 0, "callback" },
  { "errback", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, errback), 0, "errback" },
  { "with_metrics", Py_T_OBJECT_EX, offsetof(pycbc_kv_request, with_metrics), 0, "with metrics" },
  { nullptr }
};

static PyType_Slot pycbc_kv_request_slots[] = {
  { Py_tp_new, (void*)pycbc_kv_request__new__ },
  { Py_tp_dealloc, (void*)pycbc_kv_request__dealloc__ },
  { Py_tp_members, (void*)pycbc_kv_request_members },
  { Py_tp_doc, (void*)PyDoc_STR("KV Operation Request") },
  { 0, nullptr }
};

static PyType_Spec pycbc_kv_request_spec = { "pycbc_core.pycbc_kv_request",
                                             sizeof(pycbc_kv_request),
                                             0,
                                             Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
                                             pycbc_kv_request_slots };

PyObject* pycbc_kv_request_type_obj = nullptr;

int
add_kv_request_type(PyObject* module)
{
  pycbc_kv_request_type_obj = PyType_FromSpec(&pycbc_kv_request_spec);
  if (pycbc_kv_request_type_obj == nullptr) {
    return -1;
  }
  if (PyModule_AddType(module, (PyTypeObject*)pycbc_kv_request_type_obj) < 0) {
    return -1;
  }
  return 0;
}

} // namespace pycbc

// ====================================================================================================
// AUTOGENERATED FILE END - DO NOT EDIT MANUALLY
// Generated-On: 2026-08-12 14:50:38
// ====================================================================================================
