/*
 *   Copyright 2016-2026. Couchbase, Inc.
 *   All Rights Reserved.
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

// ====================================================================================================
// AUTOGENERATED FILE START - DO NOT EDIT MANUALLY
// Generated-On: 2026-04-25 14:10:18
// ====================================================================================================

#include "pycbc_dict_keys.hxx"

namespace pycbc
{
namespace keys
{

PyObject* access_deleted = nullptr;
PyObject* all_okay = nullptr;
PyObject* array_positions = nullptr;
PyObject* batch_byte_limit = nullptr;
PyObject* batch_item_limit = nullptr;
PyObject* batch_time_limit = nullptr;
PyObject* body = nullptr;
PyObject* bucket = nullptr;
PyObject* callback = nullptr;
PyObject* cas = nullptr;
PyObject* client_context_id = nullptr;
PyObject* code = nullptr;
PyObject* collection = nullptr;
PyObject* collection_id = nullptr;
PyObject* collection_name = nullptr;
PyObject* complete = nullptr;
PyObject* concurrency = nullptr;
PyObject* consistent_with = nullptr;
PyObject* content = nullptr;
PyObject* count = nullptr;
PyObject* create_as_deleted = nullptr;
PyObject* datatype = nullptr;
PyObject* date_ranges = nullptr;
PyObject* debug_info = nullptr;
PyObject* deleted = nullptr;
PyObject* delta = nullptr;
PyObject* document_exists = nullptr;
PyObject* durability_level = nullptr;
PyObject* ec = nullptr;
PyObject* effective_projections = nullptr;
PyObject* elapsed_time = nullptr;
PyObject* end = nullptr;
PyObject* end_offset = nullptr;
PyObject* errback = nullptr;
PyObject* error_count = nullptr;
PyObject* error_partition_count = nullptr;
PyObject* errors = nullptr;
PyObject* exclusive = nullptr;
PyObject* execution_time = nullptr;
PyObject* exists = nullptr;
PyObject* expiry = nullptr;
PyObject* explanation = nullptr;
PyObject* field = nullptr;
PyObject* fields = nullptr;
PyObject* flags = nullptr;
PyObject* fragments = nullptr;
PyObject* from = nullptr;
PyObject* id = nullptr;
PyObject* ids_only = nullptr;
PyObject* index = nullptr;
PyObject* initial_value = nullptr;
PyObject* is_replica = nullptr;
PyObject* key = nullptr;
PyObject* limit = nullptr;
PyObject* locations = nullptr;
PyObject* lock_time = nullptr;
PyObject* max = nullptr;
PyObject* max_score = nullptr;
PyObject* message = nullptr;
PyObject* metrics = nullptr;
PyObject* min = nullptr;
PyObject* missing = nullptr;
PyObject* more = nullptr;
PyObject* mutation_count = nullptr;
PyObject* name = nullptr;
PyObject* numeric_ranges = nullptr;
PyObject* opcode = nullptr;
PyObject* original_index = nullptr;
PyObject* other = nullptr;
PyObject* parent_span = nullptr;
PyObject* path = nullptr;
PyObject* persist_to = nullptr;
PyObject* position = nullptr;
PyObject* prefix = nullptr;
PyObject* preserve_array_indexes = nullptr;
PyObject* preserve_expiry = nullptr;
PyObject* processed_objects = nullptr;
PyObject* profile = nullptr;
PyObject* projections = nullptr;
PyObject* read_preference = nullptr;
PyObject* reason = nullptr;
PyObject* replica = nullptr;
PyObject* replicate_to = nullptr;
PyObject* request_id = nullptr;
PyObject* result_count = nullptr;
PyObject* result_size = nullptr;
PyObject* retry = nullptr;
PyObject* revive_document = nullptr;
PyObject* scan_type = nullptr;
PyObject* scan_uuid = nullptr;
PyObject* scope = nullptr;
PyObject* scope_name = nullptr;
PyObject* score = nullptr;
PyObject* seed = nullptr;
PyObject* sequence_number = nullptr;
PyObject* sequence_number_exists = nullptr;
PyObject* signature = nullptr;
PyObject* snapshot_requirements = nullptr;
PyObject* sort_count = nullptr;
PyObject* specs = nullptr;
PyObject* start = nullptr;
PyObject* start_offset = nullptr;
PyObject* status = nullptr;
PyObject* store_semantics = nullptr;
PyObject* success_partition_count = nullptr;
PyObject* term = nullptr;
PyObject* terms = nullptr;
PyObject* timeout = nullptr;
PyObject* to = nullptr;
PyObject* token = nullptr;
PyObject* tokens = nullptr;
PyObject* took = nullptr;
PyObject* total = nullptr;
PyObject* total_rows = nullptr;
PyObject* value = nullptr;
PyObject* vbucket_uuid = nullptr;
PyObject* warning_count = nullptr;
PyObject* warnings = nullptr;
PyObject* with_expiry = nullptr;
PyObject* wrapper_span_name = nullptr;

} // namespace keys
} // namespace pycbc

void
init_pycbc_dict_keys()
{
  // To be compliant with the Limited API (Stable ABI) across all versions,
  // we use PyUnicode_FromString followed by PyUnicode_InternInPlace.
  auto intern = [](const char* name) -> PyObject* {
    PyObject* s = PyUnicode_FromString(name);
    if (s) {
      PyUnicode_InternInPlace(&s);
    }
    return s;
  };

  pycbc::keys::access_deleted = intern("access_deleted");
  pycbc::keys::all_okay = intern("all_okay");
  pycbc::keys::array_positions = intern("array_positions");
  pycbc::keys::batch_byte_limit = intern("batch_byte_limit");
  pycbc::keys::batch_item_limit = intern("batch_item_limit");
  pycbc::keys::batch_time_limit = intern("batch_time_limit");
  pycbc::keys::body = intern("body");
  pycbc::keys::bucket = intern("bucket");
  pycbc::keys::callback = intern("callback");
  pycbc::keys::cas = intern("cas");
  pycbc::keys::client_context_id = intern("client_context_id");
  pycbc::keys::code = intern("code");
  pycbc::keys::collection = intern("collection");
  pycbc::keys::collection_id = intern("collection_id");
  pycbc::keys::collection_name = intern("collection_name");
  pycbc::keys::complete = intern("complete");
  pycbc::keys::concurrency = intern("concurrency");
  pycbc::keys::consistent_with = intern("consistent_with");
  pycbc::keys::content = intern("content");
  pycbc::keys::count = intern("count");
  pycbc::keys::create_as_deleted = intern("create_as_deleted");
  pycbc::keys::datatype = intern("datatype");
  pycbc::keys::date_ranges = intern("date_ranges");
  pycbc::keys::debug_info = intern("debug_info");
  pycbc::keys::deleted = intern("deleted");
  pycbc::keys::delta = intern("delta");
  pycbc::keys::document_exists = intern("document_exists");
  pycbc::keys::durability_level = intern("durability_level");
  pycbc::keys::ec = intern("ec");
  pycbc::keys::effective_projections = intern("effective_projections");
  pycbc::keys::elapsed_time = intern("elapsed_time");
  pycbc::keys::end = intern("end");
  pycbc::keys::end_offset = intern("end_offset");
  pycbc::keys::errback = intern("errback");
  pycbc::keys::error_count = intern("error_count");
  pycbc::keys::error_partition_count = intern("error_partition_count");
  pycbc::keys::errors = intern("errors");
  pycbc::keys::exclusive = intern("exclusive");
  pycbc::keys::execution_time = intern("execution_time");
  pycbc::keys::exists = intern("exists");
  pycbc::keys::expiry = intern("expiry");
  pycbc::keys::explanation = intern("explanation");
  pycbc::keys::field = intern("field");
  pycbc::keys::fields = intern("fields");
  pycbc::keys::flags = intern("flags");
  pycbc::keys::fragments = intern("fragments");
  pycbc::keys::from = intern("from");
  pycbc::keys::id = intern("id");
  pycbc::keys::ids_only = intern("ids_only");
  pycbc::keys::index = intern("index");
  pycbc::keys::initial_value = intern("initial_value");
  pycbc::keys::is_replica = intern("is_replica");
  pycbc::keys::key = intern("key");
  pycbc::keys::limit = intern("limit");
  pycbc::keys::locations = intern("locations");
  pycbc::keys::lock_time = intern("lock_time");
  pycbc::keys::max = intern("max");
  pycbc::keys::max_score = intern("max_score");
  pycbc::keys::message = intern("message");
  pycbc::keys::metrics = intern("metrics");
  pycbc::keys::min = intern("min");
  pycbc::keys::missing = intern("missing");
  pycbc::keys::more = intern("more");
  pycbc::keys::mutation_count = intern("mutation_count");
  pycbc::keys::name = intern("name");
  pycbc::keys::numeric_ranges = intern("numeric_ranges");
  pycbc::keys::opcode = intern("opcode");
  pycbc::keys::original_index = intern("original_index");
  pycbc::keys::other = intern("other");
  pycbc::keys::parent_span = intern("parent_span");
  pycbc::keys::path = intern("path");
  pycbc::keys::persist_to = intern("persist_to");
  pycbc::keys::position = intern("position");
  pycbc::keys::prefix = intern("prefix");
  pycbc::keys::preserve_array_indexes = intern("preserve_array_indexes");
  pycbc::keys::preserve_expiry = intern("preserve_expiry");
  pycbc::keys::processed_objects = intern("processed_objects");
  pycbc::keys::profile = intern("profile");
  pycbc::keys::projections = intern("projections");
  pycbc::keys::read_preference = intern("read_preference");
  pycbc::keys::reason = intern("reason");
  pycbc::keys::replica = intern("replica");
  pycbc::keys::replicate_to = intern("replicate_to");
  pycbc::keys::request_id = intern("request_id");
  pycbc::keys::result_count = intern("result_count");
  pycbc::keys::result_size = intern("result_size");
  pycbc::keys::retry = intern("retry");
  pycbc::keys::revive_document = intern("revive_document");
  pycbc::keys::scan_type = intern("scan_type");
  pycbc::keys::scan_uuid = intern("scan_uuid");
  pycbc::keys::scope = intern("scope");
  pycbc::keys::scope_name = intern("scope_name");
  pycbc::keys::score = intern("score");
  pycbc::keys::seed = intern("seed");
  pycbc::keys::sequence_number = intern("sequence_number");
  pycbc::keys::sequence_number_exists = intern("sequence_number_exists");
  pycbc::keys::signature = intern("signature");
  pycbc::keys::snapshot_requirements = intern("snapshot_requirements");
  pycbc::keys::sort_count = intern("sort_count");
  pycbc::keys::specs = intern("specs");
  pycbc::keys::start = intern("start");
  pycbc::keys::start_offset = intern("start_offset");
  pycbc::keys::status = intern("status");
  pycbc::keys::store_semantics = intern("store_semantics");
  pycbc::keys::success_partition_count = intern("success_partition_count");
  pycbc::keys::term = intern("term");
  pycbc::keys::terms = intern("terms");
  pycbc::keys::timeout = intern("timeout");
  pycbc::keys::to = intern("to");
  pycbc::keys::token = intern("token");
  pycbc::keys::tokens = intern("tokens");
  pycbc::keys::took = intern("took");
  pycbc::keys::total = intern("total");
  pycbc::keys::total_rows = intern("total_rows");
  pycbc::keys::value = intern("value");
  pycbc::keys::vbucket_uuid = intern("vbucket_uuid");
  pycbc::keys::warning_count = intern("warning_count");
  pycbc::keys::warnings = intern("warnings");
  pycbc::keys::with_expiry = intern("with_expiry");
  pycbc::keys::wrapper_span_name = intern("wrapper_span_name");
}

// ====================================================================================================
// AUTOGENERATED FILE END - DO NOT EDIT MANUALLY
// Generated-On: 2026-04-25 14:10:18
// ====================================================================================================
